/* Opcodes and enum values of the Wayland protocols used by the Wayland backend.

 Permission is hereby granted, free of charge, to any person obtaining a copy of
 this software and associated documentation files (the "Software"), to deal in
 the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do
 so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE. */

#ifndef WAYLAND_PROTOCOL_H
#define WAYLAND_PROTOCOL_H

#include <wayland-util.h>

// Interface tables generated by `wayland-scanner private-code` from wayland.xml,
// xdg-shell, xdg-decoration, xdg-output and viewporter XML. The scanner's client headers are
// not used: their inline request stubs call the variadic wl_proxy_marshal_flags().
extern const struct wl_interface wl_display_interface;
extern const struct wl_interface wl_registry_interface;
extern const struct wl_interface wl_callback_interface;
extern const struct wl_interface wl_compositor_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface wl_subcompositor_interface;
extern const struct wl_interface wl_subsurface_interface;
extern const struct wl_interface wl_region_interface;
extern const struct wl_interface wp_fractional_scale_manager_v1_interface;
extern const struct wl_interface wp_fractional_scale_v1_interface;
extern const struct wl_interface wp_viewporter_interface;
extern const struct wl_interface wp_viewport_interface;
extern const struct wl_interface wl_shm_interface;
extern const struct wl_interface wl_shm_pool_interface;
extern const struct wl_interface wl_buffer_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_pointer_interface;
extern const struct wl_interface wl_keyboard_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zxdg_output_manager_v1_interface;
extern const struct wl_interface zxdg_output_v1_interface;
extern const struct wl_interface wl_data_device_manager_interface;
extern const struct wl_interface wl_data_device_interface;
extern const struct wl_interface wl_data_source_interface;
extern const struct wl_interface wl_data_offer_interface;
extern const struct wl_interface xdg_wm_base_interface;
extern const struct wl_interface xdg_surface_interface;
extern const struct wl_interface xdg_toplevel_interface;
extern const struct wl_interface xdg_positioner_interface;
extern const struct wl_interface xdg_popup_interface;
extern const struct wl_interface zxdg_decoration_manager_v1_interface;
extern const struct wl_interface zxdg_toplevel_decoration_v1_interface;

// Opcodes are the zero-based positions of <request> and <event> elements in the
// protocol XML. WaylandCheckOpcodes() verifies each one against the generated tables.
enum {
    WP_DATA_MANAGER_CREATE_SOURCE = 0,
    WP_DATA_MANAGER_GET_DEVICE = 1,
    WP_DATA_DEVICE_START_DRAG = 0,
    WP_DATA_DEVICE_SET_SELECTION = 1,
    WP_DATA_DEVICE_RELEASE = 2,
    WP_DATA_DEVICE_EV_OFFER = 0,
    WP_DATA_DEVICE_EV_ENTER = 1,
    WP_DATA_DEVICE_EV_LEAVE = 2,
    WP_DATA_DEVICE_EV_MOTION = 3,
    WP_DATA_DEVICE_EV_DROP = 4,
    WP_DATA_DEVICE_EV_SELECTION = 5,
    WP_DATA_SOURCE_OFFER = 0,
    WP_DATA_SOURCE_DESTROY = 1,
    WP_DATA_SOURCE_SET_ACTIONS = 2,
    WP_DATA_SOURCE_EV_SEND = 1,
    WP_DATA_SOURCE_EV_CANCELLED = 2,
    WP_DATA_SOURCE_EV_DROP_PERFORMED = 3,
    WP_DATA_SOURCE_EV_FINISHED = 4,
    WP_DATA_SOURCE_EV_ACTION = 5,
    WP_DATA_OFFER_ACCEPT = 0,
    WP_DATA_OFFER_RECEIVE = 1,
    WP_DATA_OFFER_DESTROY = 2,
    WP_DATA_OFFER_FINISH = 3,
    WP_DATA_OFFER_SET_ACTIONS = 4,
    WP_DATA_OFFER_EV_OFFER = 0,
    WP_DATA_OFFER_EV_SOURCE_ACTIONS = 1,
    WP_DATA_OFFER_EV_ACTION = 2,
    WP_DISPLAY_SYNC = 0,
    WP_DISPLAY_GET_REGISTRY = 1,

    WP_REGISTRY_BIND = 0,
    WP_REGISTRY_EV_GLOBAL = 0,
    WP_REGISTRY_EV_GLOBAL_REMOVE = 1,

    WP_CALLBACK_EV_DONE = 0,

    WP_COMPOSITOR_CREATE_SURFACE = 0,
    WP_COMPOSITOR_CREATE_REGION = 1,
    WP_REGION_DESTROY = 0,
    WP_FRACTIONAL_MANAGER_DESTROY = 0,
    WP_FRACTIONAL_MANAGER_GET_SCALE = 1,
    WP_FRACTIONAL_DESTROY = 0,
    WP_FRACTIONAL_EV_PREFERRED = 0,
    WP_VIEWPORTER_DESTROY = 0,
    WP_VIEWPORTER_GET_VIEWPORT = 1,
    WP_VIEWPORT_DESTROY = 0,
    WP_VIEWPORT_SET_SOURCE = 1,
    WP_VIEWPORT_SET_DESTINATION = 2,
    WP_SUBCOMPOSITOR_GET_SUBSURFACE = 1,
    WP_SUBSURFACE_DESTROY = 0,
    WP_SUBSURFACE_SET_POSITION = 1,
    WP_SUBSURFACE_PLACE_ABOVE = 2,

    WP_SHM_CREATE_POOL = 0,
    WP_SHM_POOL_CREATE_BUFFER = 0,
    WP_SHM_POOL_DESTROY = 1,
    WP_BUFFER_DESTROY = 0,
    WP_BUFFER_EV_RELEASE = 0,

    WP_SURFACE_DESTROY = 0,
    WP_SURFACE_ATTACH = 1,
    WP_SURFACE_DAMAGE = 2,
    WP_SURFACE_FRAME = 3,
    WP_SURFACE_SET_INPUT_REGION = 5,
    WP_SURFACE_COMMIT = 6,
    WP_SURFACE_SET_BUFFER_SCALE = 8,
    WP_SURFACE_DAMAGE_BUFFER = 9,
    WP_SURFACE_EV_ENTER = 0,
    WP_SURFACE_EV_LEAVE = 1,

    WP_SEAT_GET_POINTER = 0,
    WP_SEAT_GET_KEYBOARD = 1,
    WP_SEAT_EV_CAPABILITIES = 0,

    WP_POINTER_SET_CURSOR = 0,
    WP_POINTER_RELEASE = 1,
    WP_POINTER_EV_ENTER = 0,
    WP_POINTER_EV_LEAVE = 1,
    WP_POINTER_EV_MOTION = 2,
    WP_POINTER_EV_BUTTON = 3,
    WP_POINTER_EV_AXIS = 4,
    WP_POINTER_EV_FRAME = 5,
    WP_POINTER_EV_AXIS_SOURCE = 6,
    WP_POINTER_EV_AXIS_STOP = 7,
    WP_POINTER_EV_AXIS_DISCRETE = 8,

    WP_KEYBOARD_RELEASE = 0,
    WP_KEYBOARD_EV_KEYMAP = 0,
    WP_KEYBOARD_EV_ENTER = 1,
    WP_KEYBOARD_EV_LEAVE = 2,
    WP_KEYBOARD_EV_KEY = 3,
    WP_KEYBOARD_EV_MODIFIERS = 4,
    WP_KEYBOARD_EV_REPEAT_INFO = 5,

    WP_LOGICAL_MANAGER_DESTROY = 0,
    WP_LOGICAL_MANAGER_GET_OUTPUT = 1,
    WP_LOGICAL_OUTPUT_DESTROY = 0,
    WP_LOGICAL_OUTPUT_EV_POSITION = 0,
    WP_LOGICAL_OUTPUT_EV_SIZE = 1,
    WP_LOGICAL_OUTPUT_EV_DONE = 2,
    WP_OUTPUT_RELEASE = 0,
    WP_OUTPUT_EV_GEOMETRY = 0,
    WP_OUTPUT_EV_MODE = 1,
    WP_OUTPUT_EV_DONE = 2,
    WP_OUTPUT_EV_SCALE = 3,

    WP_WM_BASE_CREATE_POSITIONER = 1,
    WP_WM_BASE_GET_XDG_SURFACE = 2,
    WP_WM_BASE_PONG = 3,
    WP_WM_BASE_EV_PING = 0,

    WP_XDG_SURFACE_DESTROY = 0,
    WP_XDG_SURFACE_GET_TOPLEVEL = 1,
    WP_XDG_SURFACE_GET_POPUP = 2,
    WP_XDG_SURFACE_ACK_CONFIGURE = 4,
    WP_XDG_SURFACE_EV_CONFIGURE = 0,

    WP_POSITIONER_DESTROY = 0,
    WP_POSITIONER_SET_SIZE = 1,
    WP_POSITIONER_SET_ANCHOR_RECT = 2,
    WP_POSITIONER_SET_ANCHOR = 3,
    WP_POSITIONER_SET_GRAVITY = 4,
    WP_POSITIONER_SET_CONSTRAINT_ADJUSTMENT = 5,
    WP_POSITIONER_SET_OFFSET = 6,
    WP_POPUP_DESTROY = 0,
    WP_POPUP_GRAB = 1,
    WP_POPUP_REPOSITION = 2,
    WP_POPUP_EV_CONFIGURE = 0,
    WP_POPUP_EV_DONE = 1,

    WP_TOPLEVEL_DESTROY = 0,
    WP_TOPLEVEL_SET_TITLE = 2,
    WP_TOPLEVEL_SET_APP_ID = 3,
    WP_TOPLEVEL_MOVE = 5,
    WP_TOPLEVEL_RESIZE = 6,
    WP_TOPLEVEL_SET_MAX_SIZE = 7,
    WP_TOPLEVEL_SET_MIN_SIZE = 8,
    WP_TOPLEVEL_SET_MAXIMIZED = 9,
    WP_TOPLEVEL_UNSET_MAXIMIZED = 10,
    WP_TOPLEVEL_SET_MINIMIZED = 13,
    WP_TOPLEVEL_EV_CONFIGURE = 0,
    WP_TOPLEVEL_EV_CLOSE = 1,

    WP_DECORATION_MANAGER_GET_TOPLEVEL_DECORATION = 1,
    WP_TOPLEVEL_DECORATION_DESTROY = 0,
    WP_TOPLEVEL_DECORATION_SET_MODE = 1,
    WP_TOPLEVEL_DECORATION_EV_CONFIGURE = 0,
};

// Enum values from the same protocol files.
enum {
    WP_SEAT_CAPABILITY_POINTER = 1,
    WP_SEAT_CAPABILITY_KEYBOARD = 2,
    WP_POINTER_BUTTON_STATE_PRESSED = 1,
    WP_POINTER_AXIS_VERTICAL_SCROLL = 0,
    WP_POINTER_AXIS_HORIZONTAL_SCROLL = 1,
    WP_KEYBOARD_KEYMAP_FORMAT_XKB_V1 = 1,
    WP_KEYBOARD_KEY_STATE_PRESSED = 1,
    WP_OUTPUT_MODE_CURRENT = 1,
    WP_SHM_FORMAT_ARGB8888 = 0,
    WP_SHM_FORMAT_XRGB8888 = 1,
    WP_TOPLEVEL_STATE_ACTIVATED = 4,
    WP_TOPLEVEL_STATE_MAXIMIZED = 1,
    WP_TOPLEVEL_DECORATION_MODE_CLIENT_SIDE = 1,
    WP_TOPLEVEL_DECORATION_MODE_SERVER_SIDE = 2,
    WP_POSITIONER_ANCHOR_TOP_LEFT = 5,
    WP_POSITIONER_GRAVITY_BOTTOM_RIGHT = 8,
    WP_POSITIONER_SLIDE_X = 1,
    WP_POSITIONER_SLIDE_Y = 2,
    WP_POSITIONER_FLIP_X = 4,
    WP_POSITIONER_FLIP_Y = 8,
};

// Linux input event codes (linux/input-event-codes.h) carried by wl_pointer.button.
enum {
    WP_BTN_LEFT = 0x110,
    WP_BTN_RIGHT = 0x111,
    WP_BTN_MIDDLE = 0x112,
};

#endif
